on: [push, pull_request, merge_group]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.15.0-dev.151+6e8493daa
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: zig build --fetch
      - run: zig build
      - run: zig build test -Dci
      - run: zig build -Dtarget=x86_64-windows -p build/windows
      # disabled because of a freetype problem from zig upgrade
      # - run: zig build -Dplatform=web -p build/web
      - run: ./gradlew assembleDebug
        working-directory: packages/android/Aztest
      - run: mkdir -p build/android && cp packages/android/Aztest/app/build/outputs/apk/debug/app-debug.apk build/android
      - uses: actions/upload-artifact@v4
        with:
          path: build

